//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectPoliklinik_Servis_Final.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class muayene
    {
        public int muayene_id { get; set; }
        public string hasta_tanisi { get; set; }
        public string tedavi { get; set; }
        public string hastakayitno { get; set; }
        public int doktor_id { get; set; }
        public Nullable<int> oda_id { get; set; }
        public Nullable<int> yatak_id { get; set; }
        public int hemsire_id { get; set; }
        public int hasta_id { get; set; }
        public Nullable<System.DateTime> hastanecikistarihi { get; set; }
    
        public virtual doktor doktor { get; set; }
        public virtual hasta hasta { get; set; }
        public virtual hemsire hemsire { get; set; }
        public virtual oda oda { get; set; }
        public virtual yatak yatak { get; set; }
    }
}
