//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectPoliklinik_Servis_Final.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class yatak
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public yatak()
        {
            this.muayene = new HashSet<muayene>();
        }
    
        public int yatak_id { get; set; }
        public bool doluluk { get; set; }
        public int oda_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<muayene> muayene { get; set; }
        public virtual oda oda { get; set; }
    }
}
